### ISSUE TITLE
Have you ever had any issues with the xepersian package?

### ISSUE THREAD

**Issue by ghost** [faryabimm/OS_course_project_961#1]
Hi

If you ever happen to have any question, then please open an issue at [the `xepersian` package issue tracker](https://github.com/persiantex/xepersian/issues) and I will be very happy to help out.

Best wishes, Vafa Khalighi (the author of the `xepersian` package)

**Comment by faryabimm** [comment]
Hi Vafa

My experience with `xepersian` has been great so far. I think I've had some minor problems with the package in the past but nothing that I can remember right now.

If there are any issues that come to my knowledge I'll be more than glad to submit the issue or - if I can - provide additional help.
Thank you and keep up the great work.
Best of regards.
